# Generated by Django 4.2.1 on 2023-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transcription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/transcribe/')),
                ('transcription_text', models.TextField(blank=True)),
                ('transcription_file', models.FileField(blank=True, upload_to='transcripts/')),
            ],
        ),
    ]
