# Generated by Django 4.2.1 on 2023-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiongo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='translationgo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
