# Generated by Django 4.2.1 on 2023-06-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transcriptiongo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/translate/')),
                ('translation_text', models.TextField(blank=True)),
                ('translation_file', models.FileField(blank=True, upload_to='translations/')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
