# Generated by Django 4.2.1 on 2023-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.ImageField(blank=True, upload_to='images/blogimages'),
        ),
    ]
