# Generated by Django 4.2.1 on 2023-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transcription_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
