# Generated by Django 4.2.1 on 2023-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
