# Generated by Django 4.2.1 on 2023-08-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='top_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
