# Generated by Django 4.2.1 on 2023-06-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transcription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
